echeancier sur prestashop au choix de paiement
alma/alma-installments-prestashop pull request #11
Opened 2020-11-12 17:12 UTC by noshette

Testé sur : 

v.1.5.6.2
Pas de message dans le paiement c'est lié à la version ?
L’icône fontawesome n'apparaît pas à coté de la méthode de paiement Alma

v.1.6.1.23
Pas de message dans le paiement c'est lié à la version ?

v.1.7.6.8
Ok

2020-11-13 13:41 UTC, olance commented
@noshette tu veux dire quoi par "Pas de message dans le paiement c'est lié à la version ?" ? ^^

2020-11-13 14:25 UTC, noshette commented
> @noshette tu veux dire quoi par "Pas de message dans le paiement c'est lié à la version ?" ? ^^

Pas très claire effectivement ^^

Quand on choisit la méthode de paiement, sur les versions < 1.7, et quand on y sélectionne Alma, ça redirige direct vers notre page de paiement, y'a pas de radio button avec la description qui apparaît (la ou j'ai placé l'échéancier)

2020-11-13 14:32 UTC, olance commented
Ah yes indeed, PrestaShop avant 1.7 effectivement c'était fait comme ça !
Le template pour le rendu du bouton de la méthode de paiement est différent, faut qu'on regarde ensemble comment on peut intégrer l'échéancier là-dedans :)

2020-11-16 18:08 UTC, noshette commented
Finalement j'ai trouvé comment afficher l'échéancier sur ps < 1.7 ;)

Il reste juste cette histoire d’icône moche et on est bon 🥇

2020-11-19 11:58 UTC, olance requested changes
See comments :)

2020-11-19 11:58 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +            $eligibilityPnX = $alma->payments->eligibility($paymentDataPnX);
I think we need some heavy refactoring here:

- `AlmaEligibilityHelper::eligibilityCheck` should be the one to loop on `$n` and check eligibility for each activated installments count:
    - Get plans activated by the merchant
    - Check amount bounds for each activated plans: skip those for which amount is outside of bounds
    - Call Alma eligibility API for activated plans that should be active for cart amount
    - Return eligibility results

Something like this:
```
$eligibilities = [];
$activePlans = [];
foreach (AlmaSettings::activatedInstallmentsPlans() as $n) { // [2,3,4]
	if ($purchaseAmount < AlmaSettings::installmentPlanMinAmount($n) || $purchaseAmount > AlmaSettings::installmentPlanMaxAmount($n)) {
		$eligibility = new stdClass();
		$eligibility->installments_count = $n;
		$eligibility->isEligible = false;
		$eligibility->constraints = array(
			"purchase_amount" => array(
				"minimum" => AlmaSettings::installmentPlanMinAmount($n),
				"maximum" => AlmaSettings::installmentPlanMaxAmount($n)
			)
		);

		$eligibilities[] = $eligibility;
	} else {
		$activePlans[] = $n;
	}
}

$paymentData = PaymentData::dataFromCart($context->cart, $context, $activePlans);
$almaEligibilities = $alma->payments->eligibility($paymentData);

$eligibilities = array_merge($eligibilities, $almaEligibilities);

function cmp_installments_count($a, $b) {
	return $a->installments_count > $b->installments_count ? 1 : ($a->installments_count == $b->installments_count ? 0 : -1);
}

usort($eligibilities, 'cmp_installments_count');
return $eligibilities;
```

- Loop on each eligibility result and and display only a button for the eligible ones

2020-11-19 11:58 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +            $eligibilityPnX = $alma->payments->eligibility($paymentDataPnX);
Do check Shoping cart footer hook controller & paymentOptions hook controller to adapt them to the new eligibility check

2020-11-19 11:58 UTC, olance commented on alma/controllers/hook/paymentOptions.php
> +                    'plans' => (array) $eligibilityPnX->paymentPlan,
See previous comment :)

2020-11-19 11:58 UTC, olance commented on alma/views/css/alma.css
> +.alma-p-fee-plan--descritpion{
```suggestion
.alma-p-fee-plan--description{
```

2020-11-19 11:58 UTC, olance commented on alma/views/templates/hook/payment_button_desc.tpl
> +        <p class="alma-p-fee-plan--descritpion">
```suggestion
        <p class="alma-p-fee-plan--description">    
```

2020-11-19 11:58 UTC, olance commented on alma/views/templates/hook/payment_button_desc.tpl
> +    <br />
identation issues?

2020-11-19 11:58 UTC, olance commented on alma/views/templates/hook/payment_button_desc.tpl
> +    <br />
+ same display changes as in displayPayment.tpl

👉 could we refactor the installments display in a single tpl file, included by both "master" templates?

2020-11-30 10:58 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +                }
Add:

```php
else {
    continue;
}
```

2020-11-30 11:48 UTC, olance requested changes

2020-11-30 11:48 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +        $installmentPlans = AlmaEligibilityHelper::eligibilityCheck($this->context);
Do something when `$installmentPlans` is empty:

- Easy option: return
- Or: if disabled button display is enabled, loop over merchant-activated installments plan and show a disabled button for each (a payment option each with `$plans => null, $disabled => true, $error > true`)

2020-11-30 11:48 UTC, olance commented on alma/views/templates/hook/displayPayment.tpl
> +    {assign var="icone_diplsay" value="disable_arrow_icone"}
```suggestion
    {assign var="iconDisplay" value="disable-arrow-icon"}
```

2020-11-30 11:48 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +                'prestashop_version' => _PS_VERSION_,
Should we rather use a boolean like `displayArrayIcon => version_compare(...)`

2020-11-30 11:48 UTC, olance commented on alma/controllers/hook/displayShoppingCartFooter.php
> +                $eligible = true;
```suggestion
                $eligible = true;
                break;
```

2020-11-30 11:48 UTC, olance commented on alma/controllers/hook/displayShoppingCartFooter.php
> +            $minimum = 9999999;
```suggestion
            $minimum = PHP_INT_MAX;
```

2020-11-30 11:48 UTC, olance commented on alma/controllers/hook/displayShoppingCartFooter.php
> +                if(!$eligibility->isEligible){
Since we're in `if(!$eligible)`, this check is not necessary

2020-11-30 11:48 UTC, olance commented on alma/includes/AlmaEligibilityHelper.php
> +            } else {
Add this to `AlmaSettings`:

```php
    public static function activeInstallmentsCounts()
    {
        $installmentsCounts = array();

        for ($n = 2; $n <= self::installmentPlansMaxN(); $n++) {
            if (self::isInstallmentPlanEnabled($n)) {
                $installmentsCounts[] = $n;
            }
        }

        return $installmentsCounts;
    }
```

and use `foreach(AlmaSettings::activeInstallmentsCounts() as $n)` :)

2020-11-30 11:48 UTC, olance commented on alma/includes/AlmaEligibilityHelper.php
> +        }
Instead, just don't call `$alma->payments->eligibility` if `$activePlans` is empty :)

2020-11-30 11:48 UTC, olance commented on alma/controllers/hook/displayShoppingCartFooter.php
> +                            $eligibilityMsg = ' ' . sprintf(
Use the loop only to identify the global min/max values, then compute the message string after the loop depending on whether `$cartTotal` is higher than global max or lower than global min

2020-11-30 11:48 UTC, olance commented on alma/includes/AlmaEligibilityHelper.php
> +        $purchaseAmount = (float) Tools::ps_round((float)$context->cart->getOrderTotal(true, Cart::BOTH), 2) * 100;
Use `almaPriceToCents`

2020-11-30 11:48 UTC, olance commented on alma/includes/AlmaEligibilityHelper.php
>              return null;
```suggestion
            return array();
```

2020-11-30 11:48 UTC, olance commented on alma/includes/AlmaEligibilityHelper.php
>              return null;
```suggestion
            return array();
```

2020-11-30 11:48 UTC, olance commented on alma/includes/AlmaEligibilityHelper.php
> +                    $eligibility = new stdClass();
Explore the option of creating a new `Alma\API\Endpoints\Results\Eligibility` ?

2020-11-30 11:48 UTC, olance commented on alma/includes/PaymentData.php
> +                'installments_count' => $installmentsCount,
Document $installmentsCount type in method's PHPDoc

2020-11-30 11:48 UTC, olance commented on alma/views/css/alma.css
> +p.payment_module a.alma-button.disable_arrow_icone:after {
```suggestion
p.payment_module a.alma-button.disable-arrow-icon:after {
```

2020-11-30 11:48 UTC, olance commented on alma/views/templates/hook/_partials/feePlan.tpl
> +                {dateFormat date= $v.due_date|date_format:"%Y-%m-%d" full = 0}
```suggestion
                {dateFormat date=$v.due_date|date_format:"%Y-%m-%d" full=0}
```

2020-11-30 11:48 UTC, olance commented on alma/views/templates/hook/displayPayment.tpl
> +{assign var="icone_diplsay" value=""}
```suggestion
{assign var="iconDisplay" value=""}
```

2020-11-30 11:48 UTC, olance commented on alma/views/templates/hook/displayPayment.tpl
> +                    <a href="#" onclick="return false;" class="disabled alma-button  {$icone_diplsay}">
```suggestion
                    <a href="#" onclick="return false;" class="disabled alma-button {$iconDisplay}">
```

2020-11-30 11:48 UTC, olance commented on alma/views/templates/hook/displayPayment.tpl
> +                    <a href="{$option.link}" class="alma-button  {$icone_diplsay}">
```suggestion
                    <a href="{$option.link}" class="alma-button {$iconDisplay}">
```

2020-11-30 16:55 UTC, noshette commented
En pj les screenshots :  
- des 3 échéanciers 
- des 'notices' php à l'install du module 
<img width="741" alt="ps1-7" src="https://user-images.githubusercontent.com/3249959/100639238-34613080-3335-11eb-96e2-99ca42ca3846.png">
<img width="623" alt="notice-php" src="https://user-images.githubusercontent.com/3249959/100639246-362af400-3335-11eb-9b0f-a00bbb80718d.png">
<img width="752" alt="ps1-5" src="https://user-images.githubusercontent.com/3249959/100639248-37f4b780-3335-11eb-845d-a39cf3169ebc.png">
<img width="1192" alt="ps1-6" src="https://user-images.githubusercontent.com/3249959/100639249-388d4e00-3335-11eb-8ef9-718e681d287b.png">

2020-12-02 09:38 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +                $logo = Media::getMediaPath(_PS_MODULE_DIR_ . $this->module->name . '/views/img/logos/alma_p'.$n.'x.svg');
```suggestion
                $logo = Media::getMediaPath(_PS_MODULE_DIR_ . $this->module->name . "/views/img/logos/alma_p${n}x.svg");
```

2020-12-02 09:38 UTC, olance commented on alma/controllers/hook/displayPayment.php
> +                $logo = $this->module->getPathUri() . '/views/img/logos/alma_p'.$n.'x.svg';
```suggestion
                $logo = $this->module->getPathUri() . "/views/img/logos/alma_p${n}x.svg";
```

2020-12-02 09:40 UTC, olance commented on alma/controllers/hook/paymentOptions.php
> +            $logo = Media::getMediaPath($baseDir . '/views/img/logos/alma_p'.$n.'x.svg');
```suggestion
            $logo = Media::getMediaPath("${baseDir}/views/img/logos/alma_p${n}x.svg");
```

2020-12-03 15:56 UTC, noshette commented
I replaced Alma logo everywhere and changed css for feesplans in payment page : 

# in module list
<img width="251" alt="modulelist1_7" src="https://user-images.githubusercontent.com/3249959/101053011-9022f800-3587-11eb-85b7-576d6a4ced5a.png">

<img width="890" alt="moduleliste1_6" src="https://user-images.githubusercontent.com/3249959/101052998-8e593480-3587-11eb-8026-19c22a00a66a.png">

# in Alma module
<img width="1183" alt="almamodule" src="https://user-images.githubusercontent.com/3249959/101053007-8f8a6180-3587-11eb-90c2-65319f6ebf30.png">

# in footer
<img width="801" alt="footer" src="https://user-images.githubusercontent.com/3249959/101053005-8f8a6180-3587-11eb-8cdd-517247fa7c50.png">

# in payment page
<img width="778" alt="payment1_5" src="https://user-images.githubusercontent.com/3249959/101052987-8b5e4400-3587-11eb-94ad-479a7b9f8ac3.png">

<img width="1212" alt="payment1_6" src="https://user-images.githubusercontent.com/3249959/101052991-8c8f7100-3587-11eb-85bf-48d4157277ed.png">

<img width="736" alt="payment1_7" src="https://user-images.githubusercontent.com/3249959/101053002-8ef1cb00-3587-11eb-8388-ff6030c6608b.png">

2020-12-18 02:48 UTC, merged