Exclusion
alma/alma-installments-prestashop pull request #12
Opened 2020-11-17 14:18 UTC by noshette

Reste à voir sur Prestashop 1.5 : 

- un problème de traduction d'une phrase contenant un lien
- un problème de lien vers un module qui n'apparait pas dans le BO

sur toute version : 
- une question sur un header location que j'ai fait
- le filtre "exclude" qui fait planter la requête
- quand on retire un produit du panier,  pas d'ajax sur le display alma (par exemple si on passe sous le min amount en supprimant un produit, ça ne change pas le message d'éligibilité tant qu'on a pas refresh le panier)

2020-12-01 11:08 UTC, olance requested changes
See comments, and:
- rename stuff like "exclude" to "excluded" wherever it makes sense
- document the `processBulkEnable`/`Disable` to explain why "enable" will exclude
- add overrides of `processFilter` and `getList` to execute our manual `exclude` filter

2020-12-03 15:01 UTC, noshette commented
- translate EN->FR : done
- fix excluded bug request : done
- fix a lot a bugs in terms of prestashop versions : done
- I added some fresh new icons on Alma tab, for each prestashop version : 

# for 1.5 it have to be a .gif (alma logo ?)
<img width="1410" alt="excluded1_5" src="https://user-images.githubusercontent.com/3249959/101044540-be043e80-357f-11eb-9d21-bebbb657fcd2.png">

# for 1.6 it's a fontawesome css class icon
<img width="1395" alt="excluded1_6" src="https://user-images.githubusercontent.com/3249959/101044553-c0ff2f00-357f-11eb-916a-1fc4959847cf.png">

# for 1.7 it's just the fontawesome class name
<img width="1383" alt="excluded1_7" src="https://user-images.githubusercontent.com/3249959/101044556-c2305c00-357f-11eb-9603-6895dd7ff1b1.png">

2020-12-04 10:01 UTC, olance commented on alma/controllers/hook/displayShoppingCartFooter.php
> +            //' Paiment en plusieurs fois - Commande non eligible car votre panier contient un produit de(s) catégorie(s) : '.$excludeListingName;
There should be a configurable sentence for the merchant in the module's config

2020-12-04 10:03 UTC, olance commented on alma/controllers/hook/getContent.php
> +                        // PrestaShop won't detect the string if the call to `l` is multiline
```suggestion
```

2020-12-04 10:05 UTC, olance commented on alma/controllers/hook/paymentOptions.php
> +        $excludeCategory = !empty($diff) ? true : false;
```suggestion
        $excludeCategory = !empty($diff);
```

2020-12-04 10:08 UTC, olance commented on alma/includes/AlmaSettings.php
> +    }
- Move to `CartData`
- Take `$cart` directly as a function argument

2020-12-04 10:15 UTC, olance commented on alma/views/css/admin/_configure/helpers/form/form.css
> +    content: "\f05e";
```suggestion
    content: "";
    display: inline-block;
    height: 100%; // ?
    width: 100%;  // ?
    background: transparent url(....) no-repeat center center;
```

2020-12-04 10:17 UTC, olance commented on alma/views/templates/hook/excludedCategories.tpl
> +-->
```suggestion
```

2020-12-16 02:37 UTC, olance approved these changes

2020-12-16 02:40 UTC, merged