Feat/mpp 89 basket items in payment only for credit
alma/alma-installments-prestashop pull request #175
Opened 2023-04-21 15:42 UTC by Benjamin-Freoua-Alma

### Reason for change

We send the cart in payload payment only for credit (>4x) + Unit test for getCartItem

[Linear task](https://linear.app/almapay/issue/MPP-89/basket-items-in-payment-only-for-credit)

### Code changes

In payload for payment we add condition if installment > 4 + Unit test for getCartItem

### How to test

_As a reviewer, you are encouraged to test the PR locally._

Make a payment with multi product in cart, with virtual product in cart, with gift product in cart. 
Same test for > 4 installment and < 4 installment and check if cart is sent in dashboard Alma for installment > 4

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] You understand the impact of this PR on existing code/features

### Non applicable

- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

2023-04-24 07:26 UTC, joyet-simon approved these changes

2023-04-28 10:13 UTC, ClaireAlma requested changes

2023-05-02 08:52 UTC, Benjamin-Freoua-Alma commented on alma/lib/Model/CartData.php
>              if (isset($productRow['gift'])) {
@ClaireAlma 
C'était fait pas Olivier à l'époque c'est pas mon code.
Dans Prestashop il y a le champs `is_gift` et `gift` (probablement une evolution de Prestashop entre les versions)
Et cette fonction permet de prendre en compte les deux. 
Cette méthode aurait besoin de refacto mais on a pas tout fait encore :/

2023-05-02 08:57 UTC, Benjamin-Freoua-Alma commented on alma/lib/Model/ProductHelper.php
> +    public function getProductsCombinations($cart, $products)
@ClaireAlma 
Cette méthode était dans CartData, on l'a déjà extraite dans ce fichier pour pouvoir faire le Test unitaire qu'on voulait.
Il est dans un dossier Model. Tu préconise quoi, de créer un nouveau fichier juste pour ces méthodes ?

2023-05-02 08:57 UTC, Benjamin-Freoua-Alma commented on alma/lib/Model/ProductHelper.php
> +    public function getProductsDetails($products)
@ClaireAlma
Cette méthode était dans CartData, on l'a déjà extraite dans ce fichier pour pouvoir faire le Test unitaire qu'on voulait.
Il est dans un dossier Model. Tu préconise quoi, de créer un nouveau fichier juste pour ces méthodes ?

2023-05-03 13:49 UTC, ClaireAlma approved these changes

2023-05-05 12:20 UTC, merged