Fix: To attach alma hook if hook exist
alma/alma-installments-prestashop pull request #178
Opened 2023-06-05 10:31 UTC by Benjamin-Freoua-Alma

### Reason for change

Fix issue with merchant where hooks aren't well hooked. Now we don't use the version of CMS but if the hook exist.

### Code changes

Add HookHelper to make the intelligents of the good hooks to hooked 

### How to test

_As a reviewer, you are encouraged to test the PR locally._

Install and/or reset the module to see if the goods are well hooked

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] You understand the impact of this PR on existing code/features

### Non applicable

- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

2023-06-07 07:57 UTC, joyet-simon commented on alma/alma.php
> +    public $confirmUninstall;
Why have you got one variable in camel case and one in snake case?

2023-06-12 07:16 UTC, ClaireAlma commented on CHANGELOG.md
> +- Fix to attach Alma hooks if hook exist
exists, and wich hook ? this description is not verbose :)

2023-06-12 07:17 UTC, ClaireAlma commented on alma/alma.php
> +    private $is_eu_compatible;
It's better to add a description

2023-06-12 07:18 UTC, ClaireAlma commented on alma/alma.php
> +     * @return bool
why remove the comment?

2023-06-12 07:19 UTC, ClaireAlma commented on alma/lib/Model/HookHelper.php
> +    private function almaHooks()
commentaire de fonction

2023-06-12 07:19 UTC, ClaireAlma commented on alma/lib/Model/HookHelper.php
> +        $almaHooks = [
pas très propre, mettre ça dans une variable de classe plutot

2023-06-12 07:25 UTC, ClaireAlma commented on alma/lib/Model/HookHelper.php
> +        foreach ($existingHooks as $hook) {
soit mettres des continue, soit un switch case

2023-06-12 07:26 UTC, ClaireAlma commented on alma/lib/Model/HookHelper.php
> +        $existingHooks = $this->hooks;
useless variable, use $this->hooks directly in the foreach

2023-06-12 08:06 UTC, ClaireAlma requested changes
We do the review in mob this afternoon?

2023-06-12 14:16 UTC, ClaireAlma approved these changes

2023-06-14 11:33 UTC, Francois-Gomis approved these changes

2023-06-20 13:00 UTC, merged