return error in 200 for mismatch for IPN
alma/alma-installments-prestashop pull request #191
Opened 2023-07-06 15:09 UTC by Benjamin-Freoua-Alma

### Reason for change

Return error on 200 in mismatch for IPN

[Linear task](https://linear.app/almapay/issue/MPP-410/refund-mismatch-need-return-200-in-ipn)

### How to test

_As a reviewer, you are encouraged to test the PR locally._

Make a mismatch and test with IPN

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] You understand the impact of this PR on existing code/features

### Non applicable

- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

2023-07-07 07:29 UTC, joyet-simon approved these changes

2023-07-07 10:11 UTC, Francois-Gomis commented on alma/lib/API/PaymentValidation.php
> +                || Instalment::STATE_PAID !== $firstInstalment->state
You must remove test on firstInstalment->state for SEPA payment

2023-07-10 07:03 UTC, ClaireAlma commented
I don't understand the description of this PR

2023-07-10 07:19 UTC, ClaireAlma commented on alma/lib/API/MismatchException.php
> +    public function __construct($message, $code = 0, $previous = null)
if you don't extend the construct, don't put it

2023-07-10 07:30 UTC, joyet-simon approved these changes

2023-07-12 07:33 UTC, Francois-Gomis approved these changes

2023-07-12 07:37 UTC, joyet-simon approved these changes

2023-07-12 07:39 UTC, ClaireAlma commented
Just edit the changelog and put the Sepa ticket in description

2023-07-12 07:41 UTC, ClaireAlma requested changes
Just edit the changelog and put the Sepa ticket in description

2023-07-12 08:58 UTC, ClaireAlma approved these changes

2023-07-25 07:56 UTC, merged