Fix: Inpage Prestashop before 16.0.12
alma/alma-installments-prestashop pull request #208
Opened 2023-08-17 17:09 UTC by Benjamin-Freoua-Alma

2023-08-18 07:14 UTC, joyet-simon approved these changes

2023-08-18 07:19 UTC, ClaireAlma commented
You need to add a description to your PR and the testing way

2023-08-18 07:20 UTC, ClaireAlma requested changes
You need to add a description to your PR and the testing way

2023-08-18 07:44 UTC, ClaireAlma requested changes
No changelog ?

2023-08-30 20:53 UTC, Francois-Gomis approved these changes

2023-09-05 07:51 UTC, merged