Remove input insurance in DOM when click on remove insurance in the widget
alma/alma-installments-prestashop pull request #284
Opened 2024-01-12 10:47 UTC by Benjamin-Freoua-Alma

### Reason for change

[Linear task](https://linear.app/almapay/issue/ECOM-1189/remove-input-insurance-in-dom-when-click-on-remove-insurance-in-the)

### Code changes

Identify if we remove the insurance via the widget and remove in the DOM the input insurance

### How to test

Add an insurance with the widget 
then remove it with the button in the widget
and add to cart to see if the insurance isn't in the cart

### Checklist for authors and reviewers

### Non applicable

2024-01-12 13:55 UTC, ClaireAlma requested changes

2024-01-12 13:55 UTC, ClaireAlma commented on alma/views/js/alma-product-insurance.js
> +                        console.log('removeInputInsurance');
tu as laissé un console.log

2024-01-12 14:38 UTC, Benjamin-Freoua-Alma commented on alma/views/js/alma-product-insurance.js
> +                        console.log('removeInputInsurance');
console.log removed :p

2024-01-15 08:25 UTC, ClaireAlma approved these changes

2024-01-15 08:25 UTC, merged