[cart-item] Integrate the block see the insurance available for the
alma/alma-installments-prestashop pull request #364
Opened 2024-04-10 14:21 UTC by Benjamin-Freoua-Alma

### Reason for change

[Linear task](https://linear.app/almapay/issue/ECOM-1598/[🧩-ps]-integrate-the-block-see-the-insurance-available-for-the-item)

### Code changes

Add block to display insurance modal clicking on the button in the cart item without insurance

### How to test

Add two same product with one insurance and see the block insurance in the item cart without insurance
_As a reviewer, you are encouraged to test the PR locally._

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] You understand the impact of this PR on existing code/features
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

### Non applicable

2024-05-20 09:31 UTC, ClaireAlma requested changes
Merge conflicts, you have to  get develop changes before we can review :)

2024-05-20 13:30 UTC, ClaireAlma commented
@Benjamin-Freoua-Alma , lint ci as failed, you need to update your component vendor in local in order to have the good PHP fixer :)

2024-05-20 13:47 UTC, ClaireAlma commented
@Benjamin-Freoua-Alma the unit tests are broken

![image](https://github.com/alma/alma-installments-prestashop/assets/110386752/01f19e12-a382-48fe-8cca-0ead5143f523)

2024-05-20 13:52 UTC, ClaireAlma requested changes

2024-05-20 13:52 UTC, ClaireAlma commented on alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
> +        $this->priceHelper = new PriceHelper(
instead of new, use the builders->getInstance

2024-05-20 13:52 UTC, ClaireAlma commented on alma/lib/Helpers/InsuranceHelper.php
> +            $settingsHelper = new SettingsHelper(
use builder

2024-05-20 14:10 UTC, Benjamin-Freoua-Alma commented
@ClaireAlma I moved the PR in draft because with the refacto there's a lot of change to be made

2024-05-20 14:11 UTC, ClaireAlma commented
> @ClaireAlma I moved the PR in draft because with the refacto there's a lot of change to be made

Ok, don't hesitate if you need help

2024-05-22 09:53 UTC, ClaireAlma approved these changes

2024-06-20 10:10 UTC, Francois-Gomis approved these changes
to big to test

2024-06-21 07:46 UTC, carine-bonnafous approved these changes

2024-07-04 08:22 UTC, Francois-Gomis approved these changes

2024-07-04 09:02 UTC, joyet-simon approved these changes

2024-07-04 09:25 UTC, joyet-simon approved these changes

2024-07-04 09:26 UTC, merged