Save Alma order shipping data
alma/alma-installments-prestashop pull request #545
Opened 2024-07-31 21:29 UTC by Francois-Gomis

### Reason for change

[[Linear task](https://linear.app/almapay/issue/MPP-LINEAR_ISSUE_ID)
](https://linear.app/almapay/issue/ECOM-1782/[-ps]-implement-new-call-to-store-shipping-data)

### Code changes

Add new hook  

### How to test

Test with old version please ! 

_As a reviewer, you are encouraged to test the PR locally._

### Checklist for authors and reviewers

- [X] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [X] The PR implements the changes asked in the referenced task / issue
- [X] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [X] The tests are relevant, and cover the corner/error cases, not only the happy path
- [X] You understand the impact of this PR on existing code/features
- [X] The changes include adequate logging and Datadog traces

### Non applicable

2024-08-06 14:18 UTC, webaaz requested changes

2024-08-07 08:33 UTC, webaaz approved these changes
It's much better

2024-08-12 09:03 UTC, Benjamin-Freoua-Alma approved these changes

2024-08-12 09:05 UTC, CamilleFljt approved these changes

2024-08-12 09:06 UTC, merged